"""add_cart_items_table

Revision ID: 439a48efa9cf
Revises: 0bcb2514276b
Create Date: 2026-07-14 01:44:19.527447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439a48efa9cf'
down_revision: Union[str, None] = '0bcb2514276b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_items_user_id', table_name='cart_items')
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.create_index('ix_cart_items_user_id', 'cart_items', ['user_id'], unique=False)
    # ### end Alembic commands ###
